---
title: "CTT Sensor Station Changelog"
author: "Meelyn M. Pandit"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("jsonlite")
library("plotly")
library('RCurl')

```

## Sensor Station Changelog

Full Sensor Station changelog

```{r, echo=FALSE, results='asis'}

json_file = getURL('https://raw.githubusercontent.com/cellular-tracking-technologies/sensor-station-software/lts_24-06.iso/changelog.json')

json_data = fromJSON(json_file)

for (version in c(1:nrow(json_data))){ # only show first three updates
  for (feature in json_data[version, 4]) {
    for(bug in json_data[version,5]){
      
    cat('##', paste0('`', 'v', json_data[version,1], '`', ','), format(as.Date(json_data[version,2]), '%B %d, %Y'), '{-}', '\n')
      cat('\n')
        cat('### Patch Notes: ', '{-}', '\n', paste('-', json_data[version, 3], '\n'))
        cat('\n')
        cat('### Features', '{-}', '\n', paste('-', feature, '\n'))
        cat('\n')
        cat('### Bug Fixes', '{-}', '\n', paste('-', bug, '\n'))
        cat('\n')
    }
  }
}

```
