---
title: "CTT Locator User Manual"
author: "support@celltracktech.com"
date: "1/21/2021"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The CTT Locator

The CTT Locator is a portal device that can receive a variety of wildlife tag signals. It is compatible with the entire radio tag line, including ES200 devices. 

# Getting Started

## In the Box

* Yagi Antenna
* BNC to SMA coaxial adapter
* SMA coaxial cable
* CTT Locator with integrated Lithium Polymer battery and USB charger port

# Powering on the Locator

To power on the Locator, press the switch to on. A blue light will immedately shine, indicating the Locator has power. After a short bootup sequence, the Locator will create a hotspot for your phone to connect to. Due to technical limitations, Android phones will need to turn off Cellular Data. This is not required on iPhone devices. 

In addition to phones, the Locator can be used with laptops, tablets, and other modern devices.

When the blue light flashes, the Locator is in its final stages of booting. It will be ready in about 10 seconds after this indication.

Connect to a WiFi network created by the Locator. 

Next, enter this full url into the browser. Note that the https:// is important:

https://locator.click/

In a few moments, a webpage will load and show the main locator screen. 

# Screen Overview

![Home View] (https://user-images.githubusercontent.com/1101026/105431612-ee816400-5c23-11eb-8a11-b1b6b08be0dd.png)

# Home View

The Home View 



