# CTT SensorStation Recommended Maintenance {#maintenance}

## Last updated September 17, 2025 {-}

## **IMPORTANT NOTE:** Recommendations maintenance for existing V2 and V3.0 - 3.2 SensorStation Owners (excludes V3.3) {-}

<div class="board-v2">

**V2 Owners:**

1. **Update your SensorStation to the latest disk image.** [details here](https://cellular-tracking-technologies.github.io/ctt_documentation/flashingComputeModule.html)
2. **Run the over-the-air update** on your SensorStation to pull down and install the latest updates since the disk image was created.
3. **Enable the Cellular Modem (if you plan to use it)**. By default, the Cellular modem is disabled once it leaves CTT. You will need to manually enable it by using the Sensor Station LCD screen, and selecting Network --> Cellular --> Enable Modem.
4. **Request and install the new FREE PowerFilter** for reducing environmental noise [here](https://airtable.com/app20NXPv7qjXDfBN/pagrBcK1muqejz5os/form) pwd: `celltracktech2025`.
5. *Optional:* **set the reboot cycle to weekly**. This will ensure your station reboots more frequently which can reconnect any FCD that may have been kicked off due to overrunning the USB bus.

</div>

<div class="board-v3x">

**V3.0 - 3.2 Owners:**

1. **Update your SensorStation to the latest disk image.** [details here](https://cellular-tracking-technologies.github.io/ctt_documentation/flashingComputeModule.html)
2. **Run the over-the-air update** on your SensorStation to pull down and install the latest updates since the disk image was created.
3. **Enable the Cellular Modem (if you plan to use it)**. By default, the Cellular modem is disabled once it leaves CTT. You will need to manually enable it by using the Sensor Station LCD screen, and selecting Network --> Cellular --> Enable Modem.
4. **Request and install the new FREE PowerFilter** for reducing environmental noise [here](https://airtable.com/app20NXPv7qjXDfBN/pagrBcK1muqejz5os/form) pwd: `celltracktech2025`.
5. *Optional:* **set the reboot cycle to weekly**. This will ensure your station reboots more frequently which can reconnect any FCD that may have been kicked off due to overrunning the USB bus.

**Problem:** Because of a new USB Bus on the V3x stations, running 3 or more FunCube Dongles (FCDs) while also running both the Cellular Modem and Wifi module (or having a permanent Ethernet -> USB connection for a wired internet connection) **may (heavy emphasis on "may" as this issue is not consistent across installs)** cause excessive heat and power drops that may result in rebooting or "kicking off" of FunCube Dongles.

**Solution #1: If you must run 3 or more FCDs**, be sure to **DISABLE whatever you are not using.** If the station is using the cellular modem, disable the Wifi. If it's using the Wifi, disable the cellular modem. If it's using hard-wired Ethernet, disable BOTH the cellular modem and wifi. This will keep the power draw on the USB bus to a minimum, so that the FCDs will not experience lower power (they are very power hungry AND they are not all built the same, so there is considerable variation in power usage).

**Solution #2: Use up to 2 FCD.** We have demonstrated normal performance with 2 or fewer FCDs even with both cell and wifi running. That said, disabling whatever you're not using just makes sense so please do that too.

</div>

<div class="board-v33">

**V3.3 Owners:**

The newest board run includes all elements of the PowerFilter, as well as heat dissipation mechanisms and a new USB Bus that avoids the aforementioned issues. **Therefore, any new V3.3 boards that ship will have the latest disk image and not require any of the additional fixes noted above.** The only recommendation for any new station is:
Check the SensorStation User Guide and connect the station to the internet and run the over the air updater so that you have the latest patch fixes before deploying your station.

</div>

**SensorStation updates are posted to the Motus forum (community.motus.org) and the CTT Support Slack group.**
