# The SensorStation Web Interface Explained {#interface}

## Accessing the Web Interface

1. Connect your Sensor Station to the internet through Wifi or through an Ethernet connection.
2. In any web browser (i.e. Google Chrome, Mozilla Firefox), type in your Sensor Station's IP address (which you can find on the LCD screen) or `sensorstation.local` into the URL bar.

## Nodes

At the very top of the page you will see the header titled **Nodes**. This is a list of Nodes the station has detected since connecting. For each Node it lists:

`Node ID`
`Last Heard` - the time of the last health report
`Node RSSI` - the RSSI of the Node signal in decibels
`Battery Voltage` - the Node's battery voltage, which can be used to estimate its remaining life. 4.2 V is very full. 3.5 Vis low. 3 V is nearly empty.
`Node Firmware Version`

## Live Tags

This is a list of unique tags (PowerTag, LifeTag or HybridTag) that have been detected by your radios since connecting to your computer. For each tag it lists:

* `Tag ID` - unique 8-digit digital ID
* `Count` - number of beeps since last page refresh
* `Alias` - for convenience, a name can be given to a particular tag and saved in the browser by hitting the `Update` button. This information is saved in your browser only. Name it whatever you'd like. Great for keeping track of particular tags during a test.
* `"Update" Button` - save the name of a particular tag to your browser
* `"Remove" Button` - reset the saved name

Below the Live Tag list is a histogram of tags detected since opening the interface. The bars indicate the number of beeps detected.

## Station

On the right-hand sidebar of the page you'll see the **Station** section, which includes various pieces of information about your SensorStation.

* `ID` - the serial number of your SensorStation (the cell modem's IMEI)
* `Software Start` - a date/time field referring to the last reboot time
* `Compute Module Serial` - the serial number of your Raspberry Pi Compute Module
* `Module Hardware` - the compute module's hardware version
* `Module Revision` - the compute module's hardware revision
* `Boot Count` - the number of times the system has been booted
* `Total Memory` - the amount of RAM currently being used by the system
* `Last Boot` - Datetime of last boot
* `Internet Gateway` -

## System Versioning Details

* `Memory Usage` - A pie chart indicating the amount of system RAM currently being used.
* `CPU Usage` - A pie chart indicating the amount of processing power currently being used.
* `Time Sync Stats` - Detailed information of how the system time is being retrieved synced (e.g. from GPS or the internet)

## SensorStation Log

A log of SensorStation activity. Includes things such as screen updates and data retrieval flushes.

## GPS

Information retrieved over GPS: Time, Satellites, Latitude, Longitude, Altitude. If there is currently no valid fix, these fields will be blank.

## Radios (1-5)

There is a display box for each Radio port. The boxes will display all new data from each Radio port as they are detected, informing you of the following:

* `Time`
* `Tag ID`
* `RSSI`
* `Node`from which it came (if applicable).

### Radio Configuration

Each of the five 434MHz radios can be individually configured to receive `Nodes`, `Tags (FSK)`, or `OOK (legacy tags)` by clicking the corresponding button. On V1 SensorStations this configuration will only persist until the next webpage refresh unless you press the "Save Radio Configuration" button below, which will save the configuration permanently to memory. For V2 SensorStations the setting is automatically saved as soon as you acknowledge the confirmation popup after clicking the `Node`, `Tag` or `OOK` buttons for a particular radio. Configurations can be changed at any time. **Note that once you have changed the radio settings, the change is immediately saved and the data will flow from whichever you changed it to; node or tag, but in order to see the text description change on the web interface, you will need to refresh the webpage.**

`Node` = CTT Nodes Only
`Tag` = CTT LifeTags, PowerTags, ES-200 and ES-150 GPS tags
`OOK` = Legacy-style LifeTag only for limited specialized project

`Clear Session Data` simply clears the scrolling log of tags displayed for each radio port. It does not delete any data from system memory.

## Data Management

The data management section is the interface through which your station data is retrieved and deleted.

## Server Utilities

From the Server Utilities section on the web interface, you can now `Update Your SensorStation` to the latest deployment build, as well as force `Check In` and force `Upload Data` to the CTT servers.

**Requirement:**

  * Because these buttons require connecting to servers via the internet, your SensorStation must be connected to the internet, either via the *on-board LTE module*, hardwired via *Ethernet* (this includes being connected to a computer via Ethernet which is connected to the internet), or wirelessly via a *WiFi adapter*.

### Updating your SensorStation

  1. With the CTT Sensor Station Overview page open in your browser, scroll down to `Server Utilities` on the right sidebar.
  2. Click the button labeled `Station Update`, which will open the `Sensor Station Software Updater` console
  3. Scroll down below the console window and click on the `Update Station` button. This will begin the update process. Be aware that the station will be pulling code from five different code bases, which may take up to several minutes depending on your connection speed.
  4. When the process is complete, you will receive a `Station connection disconnected` dialogue. **This indicates that the update is complete** and that the system has restarted. You may now click the dialogue to clear it, and then click the button at the bottom of the screen to go `Back to Main Interface`.

## Station Log

Allows you to **download** (`Download Log File`) and **PERMANENTLY DELETE** (`Clear Log File`) the system log file. Used for informational and debugging purposes.

## CTT Tag Data

The tag data is divided into `Current Data`, `Data Not Uploaded`, and `Data Already Uploaded`. Current Data is data from the last 30 minutes. After 30 minutes, data is rotated into Data Not Uploaded, which is data beyond the last 30 minutes which has not yet been uploaded to CTT servers. If there is an internet connection via cell or ethernet, an upload attempt occurs every 2 hours. After data is uploaded, it is rotated into `Data Already Uploaded` and will stay there until you explicitly delete it. The red Delete buttons will **PERMANENTLY DELETE** the corresponding data from the SensorStation. An *are you sure* dialogue will make sure you do not accidentally delete data.

## Nanotag Data

Nanotag Data uses the same scheme as CTT Tag Data, except that currently data from the last 30 minutes is unavailable from this screen. The Sensorgnome interface is separately accessible as described below.

### Nanotag Data / Sensorgnome Interface

## Sensorgnome Interface

Click the "Sensorgnome Interface" button to go to the Sensorgnome interface.

## Sensorgnome Deployment File

The Sensorgnome Deployment file can be edited here and saved by clicked `Save Changes`.

## Reboot Button

Reboots the system.
