# Materials List {#appendix-materials}

|  **Item** | **Group** | **Description** | **Part Number** | **Connection Type(s)** | **Number Required** | **Supplier Link** |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
|  A | Comm. | HO-432 Loop -- for receiving LifeTags omnidirectionally | M2 HO-432 | Type N Female | Depends on number of antennas | [Link](https://www.hamradio.com/detail.cfm?pid=H0-000720) |
|  B | Comm. | A430S10 10 element yagi -- directional antenna for receiving distant nodes and LifeTags | Diamond Antenna A430S10 | SO-238 Female | Depends on number of antennas | [Link](https://www.hamradio.com/detail.cfm?pid=H0-005816) |
|  C | Comm. | 433MHz 5dBi omni directional antenna -- for receiving nodes from any direction, up to 700 meters away in some conditions | Data Alliance A433O5 | Type N Male | Depends on number of antennas | [Link](https://www.data-alliance.net/antenna-433mhz-5dbi-omnidirectional-fiberglass-w-n-male-vhf-uhf-marine/) |
|  D | Comm. | Cable from Antenna to SensorStation | MPD Digital | Depends on antenna and SensorStation type | Depends on number of antennas | [Link](https://mpddigital.us/cable-builder/) |
|  E | Mounting Hardware | Tri-Pod | Various, Amazon |  | Depends on number of SensorStations | [Link](https://www.amazon.com/feet-Satellite-Tripod-Mount-2-Inch/dp/B0043OAI9M/ref=sr_1_3?keywords=antenna+tripod&qid=1555017820&s=electronics&sr=1-3) |
|  F | Mounting Hardware | Mast (electrical conduit) | Lowes, Home Depot, Other Hardware Stores |  | See Setup Guide | [Link](https://www.lowes.com/search?searchTerm=emt+conduit) |
|  G | AC Power | 110-250 A/C, 50Hz/60Hz, Universal power supply, USA adapter unless specified | Optional. If purchased separately its important to use 12V DC only |  |  |  |
|  H | Solar Power | Panel 100 Watt | Various | 100 Watt Panel is recommended. | one panel per station | [Link](https://www.amazon.com/s?k=100%2Bwatt%2Bsolar&i=lawngarden&rh=n%3A2972638011%2Cp_89%3ARenogy&dc&ds=v1%3AT%2BD2BnPV7bKfh93p3lElbagKUWZIoIAzfvcaH%2BrqyX8&crid=1BLLYP68V3JF2&qid=1712760954&rnid=2528832011&sprefix=100%2Bwatt%2Bsolar%2Clawngarden%2C95&ref=sr_nr_p_89_1) |
|  I | Solar Power | 12v Deep Cycle (Marine) Battery | Renogy, others |  |  | [Link](https://www.walmart.com/ip/Renogy-12V-100AH-Deep-Cycle-Hybrid-Gel-Battery-Rechargeable-for-Solar-Wind-RV-Marine-Camping-UPS-Wheelchair-Trolling-Motor-Maintenance-Free/146311625) |
|  J | Solar Power | Charge Controller | Various |  | One per station | [Link](https://www.amazon.com/Renogy-Charge-Controller-Compatible-batteries/dp/B07G1PL1B9/?th=1) |
|  K | Solar Power | Pole-mount for Solar |  | Panel can be mounted on the ground but a tilt/pole mount makes it easier to mount. | 1 set | [Link](https://www.amazon.com/WindyNation-Side-Solar-Panel-Mount/dp/B01NAKQMKW/ref=sr_1_4?keywords=solar+panel+pole+mount&qid=1552483552&s=lawn-garden&sr=1-4) |
|  L | Node | Mast | Many | The EMT for the SensorStation (2, 1.5, 1 1/4, 1 ) |  | [Link](https://www.lowes.com/pd/Common-3-4-in-Actual-75-In-Metallic-Emt-10-ft-Conduit/3129553) |
|  M | Mounting Mast | Clamp |  | This should be the size of the bottom section of your mast- usually 1 ¼ to 2" |  | [Link](https://www.lowes.com/search?searchTerm=universal+strut+pipe+strap) |
|  N | Mounting Mast | Mounting Rail | Can be useful for mounting EMT mas on building or | Two 2-3' sections |  | [Link](https://www.lowes.com/search?searchTerm=superstrut+gold-galvanized+half+slot+channel+strut) |
